Feature/12.0/housekeeping
gobluestingray/mlgmain-odoo pull request #1
Opened 2021-03-08 20:15 UTC by traviswaelbro

This adds the minimum amount of repository configuration for Blue Stingray to do local development for Mesa Logistics.

This is primarily just adding Docker configurations and scaffolding used by Blue Stingray's internal toolset. These are not things that will be used in a staging or production environment.

---

If you are reviewing this PR, please ensure you can build and run this locally without any issues. Try creating a new database as well as restoring [this database](https://drive.google.com/drive/folders/11JCcJAASLpKTxWnnlRL70jKM6KhC__gj) (which does not have the filestore).

2021-03-08 20:24 UTC, traviswaelbro commented
Be aware: any development for Mesa Logistics will need to be checked on a demo database _and_ a production copy. There are Studio customizations in place and we have to ensure anything we're adding works with those customizations.

We may encounter cases where Studio customizations need to be created the old fashioned way and write a migration to auto-populate our custom field. For example, there may be a Studio created field that Mesa wants us to use in some custom functionality. In those cases, the Studio field will be manually removed on Production afterwards.

2021-03-09 01:17 UTC, manney commented
Also be nice in these PRs.  :slightly_smiling_face:

2021-03-09 01:25 UTC, manney commented
So are we holding off on putting the rest of the project scaffold on to this until Odoo's hours are used up?

2021-03-09 02:42 UTC, manney requested changes
Potential other changes I'm getting:
* On build each of these items make it fail:
  * `mlgmain-odoo/.container/env/odoo` doesn't exist.  Should we put it in here?
  * `mlgmain-odoo/.container/env/postgres` doesn't exist.  Should we put it in here?
    * **Note:** These are both referenced in `docker-compose.yml`
  * The `Dockerfile` for the database doesn't exist.  What version of postgres do they use?
  * The `Dockerfile` for Odoo (`web`) doesn't exist.  How is that set up?
    * **Note:** I copied these `Dockerfile`s from our other 12 project
* It's not showing styles when I load it up and it wants me to create/restore a database

And, I cannot get it properly working.  I'll see if killing it and starting from scratch gets me anywhere.

2021-03-09 02:42 UTC, manney commented on .container/config/odoo.conf.sample
> +    /opt/odoo/vendor/_lib,
Do we need this in here:
```suggestion
    /opt/odoo/enterprise,
    /opt/odoo/vendor/_lib,
```

2021-03-09 13:47 UTC, manney commented
> @manney No wonder you were having issues. Half of the docker files were being ignored when I committed.

This thing needs a crying emoji as a reaction.  :sob:

2021-03-09 13:49 UTC, manney commented
I'll try it again in a bit.  :crossed_fingers:

2021-03-09 16:36 UTC, manney commented
Okay, still missing the stuff that goes into `_lib_static` but looking better already for me.

2021-03-10 17:43 UTC, slsanc commented
Probably something on my end, but the project spins up fine, and the logs look normal, but when I try to view it in the browser, the connection resets.

![Screenshot from 2021-03-10 11-40-53](https://user-images.githubusercontent.com/64165094/110672692-87991980-8195-11eb-84f1-00390cd998b2.png)

2021-03-10 17:48 UTC, manney commented
It's still missing a couple of modules, but you should be able to get it to the "database selector" page so you can create a new db.

2021-03-10 20:07 UTC, traviswaelbro commented
@slsanc Are you able to access localhost:10102/web/database/manager?

2021-03-10 22:14 UTC, manney commented
@traviswaelbro Any luck on those missing modules?

2021-03-10 22:26 UTC, slsanc commented
> Are you able to access localhost:10102/web/database/manager

No.

2021-03-11 05:11 UTC, traviswaelbro commented
> @traviswaelbro Any luck on those missing modules?

No, I'll ask Joe to reach out to James. I've got a couple things I've been waiting on for a few days

2021-03-11 05:11 UTC, traviswaelbro commented
@slsanc We can take a look at your local during our meeting in the morning

2021-03-12 02:29 UTC, traviswaelbro commented
We were able to resolve Scott's issues by recloning and rebuilding the repository.

James stated he isn't aware of the theme modules being installed. I'll be working with him to try to figure out why they're loaded in and how we can get copies of them. In the meantime, can we go ahead and merge this as is? We're going to have additional PRs coming through and it's going to be convoluted if they all have the housekeeping changes showing up as well.

2021-03-12 16:32 UTC, manney commented
:sob:

2021-03-12 16:39 UTC, manney approved these changes

2021-03-12 16:39 UTC, manney commented on .container/env/odoo/Dockerfile
> +# RUN set -x; dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
Should you just remove this?

2021-03-12 16:39 UTC, manney commented on .container/env/odoo/Dockerfile
> +RUN ${PIP_EXE} install websocket-client
I think you like this on one line?  I think it's better like this that way if one fails you have everything before it cached on build.  But :man_shrugging:

2021-03-12 16:39 UTC, manney commented on .container/env/odoo/Dockerfile
> +RUN ${PIP_EXE} install websocket-client
Also if you have the above commented out / removed, should this be removed as well?

2021-03-12 16:39 UTC, manney commented on requirements.txt
> +pre_commit==1.12.*
Oooh need to update these, too, since I just did the project scaffold.  Might not work now that I told git to ignore changes on this file, though.

2021-03-12 16:40 UTC, manney commented
I've approved it as requested, but we're still missing the theme modules that are needed for installing the db, I think.

2021-03-12 19:10 UTC, traviswaelbro commented
Well I made those updates but it didn't actually force a reapproval 🤔 

I requested it by accident as I realized that 😅

2021-03-12 19:23 UTC, manney approved these changes

2021-03-16 14:18 UTC, traviswaelbro commented
@slsanc bump

2021-03-17 17:53 UTC, slsanc approved these changes

2021-03-18 04:47 UTC, merged