[ADD] Mesa Purchase Module
gobluestingray/mlgmain-odoo pull request #3
Opened 2021-03-12 18:38 UTC by slsanc

**[#12805 Auto populate Sales rep on Bill's based on PO [15505]](https://erp.bluestingray.com/web#id=15505&view_type=form&model=project.task&action=378&menu_id=263)**
**[#12816 Auto populate Sales rep on PO's based on Related Customer [15504]](https://erp.bluestingray.com/web#id=15504&view_type=form&model=project.task&action=378&menu_id=263)**

This commit creates the mesa_purchase module. This module adds the following features:
- When a user creates a Vendor Bill from a Purchase Order, the default Sales Representative for the Vendor Bill is now the Sales Representative of the Purchase Order.
- When a user changes the Related Customer of a Purchase Order, the Sales Representative of the Purchase Order is set to the new Related Customer’s Sales Representative.

2021-03-12 18:58 UTC, traviswaelbro reviewed
I haven't reviewed this yet, but a couple of early comments.

1. We want to avoid having modules which are too broad/generic and I'm worried we'll fall into that trap by having this be `mesa_purchase`, "Mesa specific purchase features". Instead, can we tailor the naming and description of these to be a bit more specific/focused, such as `mesa_purchase_default_salesperson` or similar?
2. What happens if you try to install this on a database without `x_studio_related_customer`?

2021-03-15 16:02 UTC, toddythebody commented on mesa_purchase/models/purchase/order.py
> +        """
You still need to have your `:return` in there even if you're using core code.  Also if you're overriding, add `### Custom Code Begin ###` and `### Custom Code End ###` around your code.

2021-03-15 17:51 UTC, slsanc commented on mesa_purchase/models/purchase/order.py
> +    force_user_id = fields.Many2one("res.users", string="Responsible Salesperson (Custom)", store=True)
I just looked elsewhere and see that `some_field_id` and `force_some_field_id` are generally both stored. I will make it so here.

2021-03-15 18:55 UTC, slsanc commented
> I haven't reviewed this yet, but a couple of early comments.
> 
>     1. We want to avoid having modules which are too broad/generic and I'm worried we'll fall into that trap by having this be `mesa_purchase`, "Mesa specific purchase features". Instead, can we tailor the naming and description of these to be a bit more specific/focused, such as `mesa_purchase_default_salesperson` or similar?
> 

@traviswaelbro  I was going off of the copper_inventory module and others I'd seen in our codebase. But I understand now that those are considered legacy, and we have changed practices.

>     2. What happens if you try to install this on a database without `x_studio_related_customer`?

The install fails. But we need to either reference that field here or replace the studio field with a field in the code. I started doing this, but I realized that:
1 - Replacing even one of the studio fields would mean having to replace them all, because so many of the studio fields rely on each other.
2 - the developers at Odoo are working around these studio fields, so we probably can't undertake the task of replacing the studio fields until their time has run out.

2021-03-15 18:58 UTC, slsanc commented on mesa_purchase/models/purchase/order.py
> +            purchase_id.user_id = purchase_id.x_studio_related_customer.user_id.id
I'm not quite sure what you mean. It is being declared on line 8, then used in the inverse_user_id function. Should I take out line 8?

2021-03-16 14:47 UTC, traviswaelbro requested changes
Couple of minor comments. Functionally tested and looking good overall. 👍

2021-03-16 14:47 UTC, traviswaelbro commented on mesa_purchase_default_salesperson/__manifest__.py
> +    'version': '12.0.0',
Why isn't black running automatically?

```suggestion
    "name": "Mesa Purchase Default Salesperson",
    "category": "Purchase",
    "version": "12.0.0",
```

2021-03-16 14:47 UTC, traviswaelbro commented on mesa_purchase_default_salesperson/models/purchase/order.py
> +        """
You need to write your own docstring when you're inheriting/overriding a method. It should explain whether you're inheriting or overriding and why you're doing that or what you're changing.

2021-03-16 14:47 UTC, traviswaelbro commented on mesa_purchase_default_salesperson/models/purchase/order.py
> +                ### Custom Code Begin ###
We usually use

```
### BEGIN CUSTOM CODE ###
...
### END CUSTOM CODE ###
```

2021-03-16 14:47 UTC, traviswaelbro commented on mesa_purchase_default_salesperson/models/purchase/order.py
> +        This allows users to manually set the LOB field in the form.
I don't think Mesa uses LOB 😉

2021-03-16 18:08 UTC, toddythebody commented on mesa_purchase_default_salesperson/models/purchase/order.py
> +        This allows users to manually set the LOB field in the form.
Maybe we should introduce it to them.  Seems to be a great concept for our other client.

2021-03-16 18:12 UTC, toddythebody requested changes

2021-03-16 18:12 UTC, toddythebody commented on mesa_purchase_default_salesperson/models/purchase/order.py
> +        :return: an action that displays vendor bills of
What are the types?  What are the possible actions?  What causes each action?

2021-03-16 21:32 UTC, slsanc commented on mesa_purchase_default_salesperson/models/purchase/order.py
> +        This allows users to manually set the LOB field in the form.
@traviswaelbro @toddythebody 

This is terribly embarrassing. :flushed: 
To be completely honest, I had copied and pasted the inverse function from a copper module. I need to be very careful about doing this.

2021-03-17 18:58 UTC, toddythebody approved these changes

2021-03-17 19:02 UTC, slsanc commented
@toddythebody that I made the force_user_id field stored, based on Aaron's advice regarding force fields [here](https://github.com/gobluestingray/mlgmain-odoo/pull/4#discussion_r595586547)

2021-03-22 14:14 UTC, traviswaelbro requested changes

2021-03-22 22:53 UTC, closed without merging

2021-03-22 22:53 UTC, slsanc commented
This has been moved to:
https://github.com/gobluestingray/mlgmain-odoo/pull/5