[ADD] Mesa Expense Autopopulate Feature
gobluestingray/mlgmain-odoo pull request #4
Opened 2021-03-16 15:44 UTC by slsanc

This commit adds the Mesa Expense Autopopulate module, which automatically fills in several fields on Expense records when a user sets the Expense's Sale Order. More specifically, it sets the Expense's Project, Sales Team, Warehouse, Salesperson, and Company to match the corresponding fields on the Sales Order.

2021-03-16 22:03 UTC, manney commented
This is a relatively new requirement, but please rename the PR to the branch name.

2021-03-16 22:59 UTC, manney requested changes
Untested.  But lots of comments on this one.  I'd also like to see a test or two for the changes you've made.

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    )
Is this another Studio field?  Might need a comment if so.  If not, shame on you for such a non-style guide field name.  :wink:

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    )
Also, can you please alphabetize the field definitions?  Not sure if it's in the style guide, but it does help maintenance in the long run.

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/__manifest__.py
> +    "depends": ["hr_expense", "sale_expense", "web"],
```suggestion
    "depends": ["hr_expense", "sale_expense", "web", "gross_margin"],
```

`gross_margin` has the field definitions for `hr.expense` fields: `team_id`, `warehouse_id`, and `user_id`.

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    # The following studio field is only included here because the database would otherwise not let this module install.
```suggestion
    # The following studio field is only included here because the database
    # would otherwise not let this module install
```

Try to keep comments at 80 columns unless indentation makes it hard to read.

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    @api.depends("sale_order_id")
```suggestion
    @api.depends("sale_order_id.x_studio_project")
```
You should probably include the field you're actually using in your dependency list.  Like if someone were to change the project on the sale order, Odoo wouldn't recompute the field.

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    company_id = fields.Many2one(compute="_compute_company", inverse="_inverse_company")
Looks like all of these fields have `inverse`s, so you'll need to `store=True` them.  You also need to create your inverse fields that you've used below, but not defined here.  Make sure to `store=True` them as well, please.

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    @api.depends("sale_order_id")
The same goes for all of the `compute`s below.

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +            )
Question: Is this supposed to change the sale order field's value or just be for this expense record?

```suggestion
            project_name = expense_id.sale_order_id.x_studio_project
            project_id = self.env["project.project"].search([("name", "=", project_name)], limit=1)
            
            expense_id.x_studio_field_Evfct = expense_id.force_project_id.id or project_id.id
```

2021-03-16 22:59 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +            expense_id.team_id = expense_id.sale_order_id.team_id
This needs to happen on the rest of your computes with inverses as well, please.

Also, don't forget the `.id` after whatever you're assigning to the `Many2one` field.  Same on the below computes and inverses.  As long as it's assigning a record to a `Many2one`, then you should probably have it in there.  If it's a `Char`, `Integer`, etc you don't need it because it isn't holding another record's "link" (if you will.)

```suggestion
            expense_id.team_id = expense_id.force_team_id.id or expense_id.sale_order_id.team_id.id
```

2021-03-16 22:59 UTC, manney commented on requirements.txt
> -pysftp
Need to keep `pysftp` in here.

2021-03-18 15:01 UTC, traviswaelbro commented on mesa_expense_autopopulate/models/hr/expense.py
> +    x_studio_field_Evfct = fields.Many2one(
If we are replacing Studio fields, can we please give them normal names? The Studio fields will be deleted after we implement this. We don't want to give our fields Studio names because it's misleading to us and the Odoo developers.

2021-03-18 15:03 UTC, traviswaelbro commented on mesa_expense_autopopulate/models/hr/expense.py
> +    x_studio_aa_update = fields.Many2one("account.analytic.account")
Can they still delete their Studio fields if we have them in our module? If not, then we need to either remove this field definition or replace the field.

2021-03-18 15:06 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    x_studio_aa_update = fields.Many2one("account.analytic.account")
We need to make sure that we can move the data over from existing Studio fields to our fields before they delete them (if they can.)

2021-03-18 15:11 UTC, traviswaelbro commented on mesa_expense_autopopulate/models/hr/expense.py
> +    x_studio_aa_update = fields.Many2one("account.analytic.account")
Yes, if there's a Studio field that we need to replace with a standard custom field, then the expectation was to create the standard custom field and write a migration to convert the data before getting approval from James to delete the Studio field

2021-03-19 00:45 UTC, manney commented
I'm going to make this PR go to `dev-12.0` instead of the now merged "housekeeping".

2021-03-19 00:46 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    x_studio_field_Evfct = fields.Many2one(
Make sure to update any other references to that [faux-] studio field.

2021-03-22 14:14 UTC, traviswaelbro commented
@slsanc what is left before this is ready for review?

2021-03-22 22:57 UTC, slsanc commented
This has been moved to
https://github.com/gobluestingray/mlgmain-odoo/pull/5

2021-03-22 22:57 UTC, closed without merging