feature/12.0/15510/replace_studo_project_fields
gobluestingray/mlgmain-odoo pull request #5
Opened 2021-03-22 20:39 UTC by slsanc

[WIP] Replace Studio Project Field with non-studio field

This commit works towards several related tasks, all of which require the replacement of the studio Project field with a non-studio field.

2021-03-22 23:18 UTC, slsanc commented
Some notes from previous PRs:

@traviswaelbro  asked:

> Can they still delete their Studio fields if we have them in our module? If not, then we need to either remove this field definition or replace the field

I checked and didn't get any issue with deleting the Project or Analytic studio fields, but I (predictably) get issues when I try to remove x_studio_related_customer from the Purchase Order model - the compute for Purchase Orders' Sales Rep relies upon that studio field.

> Can this be done without a force_user_id? I think the _inverse_user_id could just pass and this would work the same way. Just wondering if there's a way to do this without the extra force_ fields because they usually seem like overkill
I like the force_fields for a couple of reasons:

I plan on trying this tomorrow! Just a thought though - without a force_field as a second option, wouldn't the _compute_field(self) method just reset the field right after a user tries to change it?

2021-03-23 14:58 UTC, manney requested changes
Got a few things in there to have another look at.

2021-03-23 14:58 UTC, manney commented on mesa_crm_lead_projects/models/crm/lead.py
> +                crm_lead.project_id = crm_lead.project_ids[0].id
Would something like this work?  The `filtered()` in the `for` cuts out the leads that don't have any projects.  The switch from `[0]` to `[:1]` just makes sure that there isn't an error if there isn't a record.

```suggestion
        for crm_lead in self.filtered('project_ids'):
            crm_lead.project_id = crm_lead.project_ids[:1].id
```

2021-03-23 14:58 UTC, manney commented on mesa_crm_lead_projects/models/project/project.py
> +            project_id.x_studio_field_IxF50 = project_id.opportunity_id.id
I'm not even sure what you're doing here.  Why are we keeping `IxF50` around?

2021-03-23 14:58 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    force_warehouse_id = fields.Many2one("stock.warehouse", store=True)
Can we keep these in alphabetical format with the others, please?  I also want `string="<some name>"` on all of them too, please.

2021-03-23 14:58 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    )
```suggestion
    project_id = fields.Many2one(
        "project.project",
        string="Project",
        compute="_compute_project",
        inverse="_inverse_project",
        store=True,
    )
```

2021-03-23 14:58 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    force_warehouse_id = fields.Many2one("stock.warehouse", store=True)
Sorry, can we also get the methods in alphabetical order too?  This will make everything easier to find.

2021-03-23 14:58 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +            expense_id.force_project_id = expense_id.x_studio_field_Evfct.id
What is going on here?
```suggestion
            expense_id.force_project_id = expense_id.project_id.id
```

2021-03-23 14:58 UTC, manney commented on mesa_purchase_autopopulate/models/purchase/order.py
> +    )
You don't need a `string` if the related field is already named what you want it to be.  So if `sale_order_id.project_id`'s `string` is `Project` then you don't need to add a `string` here.

2021-03-23 14:58 UTC, manney commented on mesa_purchase_autopopulate/models/purchase/order.py
> +    )
Again, please alphabetize these with the rest of the fields.

2021-03-23 14:58 UTC, manney commented on mesa_purchase_autopopulate/models/purchase/order.py
> +                result["res_id"] = self.invoice_ids.id or False
I think this will help others see what you've done a bit better.  It took me a minute to compare it to Core to see what you did.  :slightly_smiling_face: 
```suggestion

            ### BEGIN CUSTOM CODE ###
            if create_bill:
                # If we want to create a Vendor Bill, Set the Purchase Order's
                # Purchase Representative as the Vendor Bill's default
                # Purchase Representative.
                result["context"]["default_user_id"] = self.user_id.id
            else:
                # Do not set an invoice_id if we want to create a new bill.
                # if not create_bill:
                ### END CUSTOM CODE ###
                result["res_id"] = self.invoice_ids.id or False

```

2021-03-23 14:58 UTC, manney commented on mesa_sale_autopopulate/models/sale/order.py
> +        "project.project", string="Project", related="opportunity_id.project_id"
Same comment about the `string` as above.

2021-03-23 14:58 UTC, manney commented on mesa_sale_autopopulate/models/sale/order.py
> +    )
Same comment about alphabetizing as above.

2021-03-23 14:58 UTC, manney commented on vendor_pricelist/views/purchase_order.xml
> +</odoo>
Any reason why this entire file shouldn't be removed?

2021-03-23 15:07 UTC, slsanc commented on mesa_crm_lead_projects/models/project/project.py
> +            project_id.x_studio_field_IxF50 = project_id.opportunity_id.id
Because IxF50 is the current studio field for Opportunity, and other studio fields depend on it. If I were to leave this out, things that should change when the Opportunity is changed wouldn't.

One solution is to make all of those dependent fields non-studio, but that is a lot of work and is probably outside of the scope of these tasks. My solution is to set the studio field equal to the non-studio field.

2021-03-23 15:14 UTC, slsanc commented on mesa_purchase_autopopulate/models/purchase/order.py
> +                result["res_id"] = self.invoice_ids.id or False
> Which PR were those notes from?

The Purchase Autopopulate Module.

2021-03-23 15:23 UTC, slsanc commented on mesa_crm_lead_projects/models/crm/lead.py
> +                crm_lead.project_id = crm_lead.project_ids[0].id
This works exactly the same - is there any performance benefit to this?

2021-03-23 15:29 UTC, slsanc commented on mesa_expense_autopopulate/models/hr/expense.py
> +    force_warehouse_id = fields.Many2one("stock.warehouse", store=True)
@manney  do you mean that all the force_fields should come between company_id and project_id?

2021-03-23 15:29 UTC, manney commented on mesa_crm_lead_projects/models/crm/lead.py
> +                crm_lead.project_id = crm_lead.project_ids[0].id
Potentially less iterations in the `for` loop.  If you do it the other way, then the `for` loop iterates over all of the leads whether they have projects or not.

2021-03-23 15:32 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    force_warehouse_id = fields.Many2one("stock.warehouse", store=True)
So:
```
company_id
force_company_id
force_project_id
force_team_id
force_user_id
force_warehouse_id
project_id
team_id
user_id
warehouse_id
...

2021-03-23 15:33 UTC, manney commented on mesa_expense_autopopulate/models/hr/expense.py
> +    force_warehouse_id = fields.Many2one("stock.warehouse", store=True)
At least that's how I doing in these days.  It makes a field/method easier to find.

2021-03-23 15:48 UTC, slsanc commented on vendor_pricelist/views/purchase_order.xml
> +</odoo>
Apparently, that whole module was developed by Odoo. It will probably get deleted when they are no longer on Mesa.

2021-03-23 19:00 UTC, slsanc commented
Update: I did in fact remove all of the force_fields. Functionality is unchanged. I also replaced Purchase Orders' Related Customer with a non-studio field. I also added the new non-studio field to the Purchase Order form view.

2021-03-24 13:23 UTC, manney commented
> Update: I did in fact remove all of the force_fields. Functionality is unchanged. I also replaced Purchase Orders' Related Customer with a non-studio field. I also added the new non-studio field to the Purchase Order form view.

Let's make sure we keep an eye on those.  I'm worried that a change in the value of a field that the compute depends on will wipe out the "custom" value or the value will be "lost" somehow.  I've seen it before on other projects.

2021-03-24 13:33 UTC, manney requested changes
A quick nitpick.

2021-03-24 13:33 UTC, manney commented on mesa_crm_lead_projects/models/crm/lead.py
> +    )
Sorry, missed this one.  Please alphabetize for clarity.

2021-03-24 18:34 UTC, slsanc commented on mesa_purchase_autopopulate/models/purchase/order.py
> +    )
In Mesa's database, Sale Orders have no field 'project_id". they have a field "project_ids", which is a Many2many field, but they do not use this. They expect each Sale Order to list either one or zero Projects.

I will however remove the string for Analytic Account - I see this is redundant.

2021-03-24 18:37 UTC, slsanc commented on mesa_sale_autopopulate/models/sale/order.py
> +        "project.project", string="Project", related="opportunity_id.project_id"
In Mesa's database, Sale Orders have no field 'project_id". they have a field "project_ids", which is a Many2many field, but they do not use this. They expect each Sale Order to list either one or zero Projects.

I will however remove the string for Analytic Account - I see this is redundant.

2021-03-25 13:47 UTC, manney approved these changes

2021-03-25 20:41 UTC, traviswaelbro reviewed
Some questions

2021-03-25 20:41 UTC, traviswaelbro commented on mesa_crm_lead_projects/models/crm/lead.py
> +            crm_lead.project_id = crm_lead.project_ids[:1].id
These should be combined into a single compute method since they share the same depends.

2021-03-25 20:41 UTC, traviswaelbro commented on mesa_crm_lead_projects/models/project/project.py
> +            project_id.x_studio_field_IxF50 = project_id.opportunity_id.id
This makes me uncomfortable 🤢

2021-03-25 20:41 UTC, traviswaelbro commented on mesa_expense_autopopulate/models/hr/expense.py
> +        pass
It's not necessarily "recommended", but you could also just use `inverse="True"` in the field definition and it would have the same effect as a `pass` inverse method. At least that's worked in recent versions of Odoo.

2021-03-25 20:41 UTC, traviswaelbro commented on mesa_purchase_autopopulate/models/purchase/order.py
> +    )
I think Aaron's point is that the `string` value would be defaulted to whatever the `string` is on the related field (`sale_order_id.project_id`).

2021-03-25 20:41 UTC, traviswaelbro commented on mesa_purchase_autopopulate/models/purchase/order.py
> +        return result
Could this just be inherited instead of completely overriding?

```python
def action_view_invoice(self):
    result = super().action_view_invoice()

    if create_bill:
        result["context"]["default_user_id"] = self.user_id.id
            
    return result
```

2021-03-25 20:41 UTC, traviswaelbro commented on mesa_purchase_autopopulate/models/purchase/order.py
> +        pass
Why do these need to be computes? Can we just make them related fields instead? Same could be said for the computed fields in `mesa_expense_autopopulate` and ` mesa_sale_autopopulate`.

2021-03-26 01:08 UTC, slsanc commented on mesa_purchase_autopopulate/models/purchase/order.py
> +        pass
I have tried replacing the computes with related fields - it caused several other things to break. I started getting security errors when trying to create certain types of records. I could spend some more time later trying to get it to work, but for now, this is working as expected.

2021-03-26 02:13 UTC, traviswaelbro approved these changes

2021-03-26 02:15 UTC, merged